### ISSUE TITLE
brew install fails

### ISSUE THREAD

**Issue by mardlin** [paritytech/homebrew-paritytech#19] opened 2016-08-31 12:14 UTC
I previously had parity running without issue, but decided to upgrade to 1.3. I started following the instructions to install rust then build with the [Quick install](https://github.com/ethcore/parity#quick-install) method, but then realized that I could use brew with the `--beta` flag instead. I stopped that process, and completely uninstalled rustup and cargo, but now am having issues with the brew installation. 

```
$ brew install parity
==> Installing parity from ethcore/ethcore
==> Cloning https://github.com/ethcore/parity.git
Updating /Users/administrator/Library/Caches/Homebrew/parity--git
==> Checking out branch stable
==> multirust update stable
Last 15 lines from /Users/administrator/Library/Logs/Homebrew/parity/01.multirust:
2016-08-31 07:54:56 -0400

multirust update stable


READ THIS: https://git.io/brew-troubleshooting
```

The result is the same with or without the `--beta` flag.

The contents of /Users/administrator/Library/Logs/Homebrew/parity/01.multirust are:

```
2016-08-31 08:08:08 -0400

multirust update stable


HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 1b6908f41e874040d29e7c698b7dd83b037bc61d
Last commit: 16 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 85505a96e273761bc764d127e19c264bd73c89ae
Core tap last commit: 51 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
GCC-4.2: build 0
Clang: 7.3 build 703
Git: 2.7.4 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
OS X: 10.11.6-x86_64
Xcode: N/A
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/Homebrew/os/mac/pkgconfig/10.11
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/Homebrew/shims/super:/usr/local/opt/multirust/bin:/usr/local/opt/gnupg2/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
```

I've run `brew doctor` and addressed all warnings.

**Comment by BCpowerup** [comment] 2016-09-19 22:28
same problem, fail to install

**Comment by bogdan-toma** [comment] 2016-11-24 09:04
Seems to be caused by a conflict on rust installation via rustup.
Fixed using:
brew uninstall multirust
brew install multirust

**Comment by debris** [comment] 2017-05-19 14:36
we use prebuilt binaries now, closing

**Closed by debris** 2017-05-19 14:36 UTC

**Comment by tcsiwula** [comment] 2017-09-05 19:35
error: struct field shorthands are unstable (see issue #37340)

**Comment by debris** [comment] 2017-09-05 22:03
@tcsiwula this error indicates that your rust version is outdated. You need at least 1.19 to build parity from source

### BUT

latest formula installs prebuilt binaries, so you don't need rust at all. simply run `brew update` before `brew install parity`

**Comment by murich** [comment] 2017-09-09 20:52
$ brew update
Already up-to-date.
$ brew upgrade parity
==> Upgrading 1 outdated package, with result:
paritytech/paritytech/parity 1.7.0
==> Upgrading paritytech/paritytech/parity --stable
==> Downloading http://d1h4xl4cr1h0mo.cloudfront.net/v1.6.10/x86_64-apple-darwin/parity
Already downloaded: ~/Library/Caches/Homebrew/parity-1.6.10
Error: Empty installation
